"""Extract only numeric motion/event data; never collapse states sharing a clip."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
source = ROOT.parent / 'work/autoparry/damage-catalog/native-cast-timing.json'
catalog = json.loads(source.read_text(encoding='utf-8'))
controller = next(c for c in catalog['controllers'] if c['data'].get('m_Name') == 'AnimationWrapper')
data = controller['data']
names = dict(data['m_TOS'])
clips = {(c['file'], c['path_id']): c for c in catalog['clips']}
fire_kinds = {'CreateBasicAttackProjectile': 0, 'CreateDashAttackProjectile': 1, 'CreateSpecialAttackProjectile': 2}
begin_events = {'BeginAttackAnimation', 'BeginDashAttackAnimation', 'BeginSpecialAttackAnimation'}

def number(value):
    return format(float(value), '.17g') + 'd'

lines = ['// Generated by generate-dps-motions.py. State identity preserves speed differences.',
         'using System.Collections.Generic;', 'namespace SephiriaDicePreview', '{',
         '    internal static class DpsMotions', '    {',
         '        internal sealed class Fire { internal int Kind,Index; internal double Time; internal Fire(int kind,int index,double time){Kind=kind;Index=index;Time=time;} }',
         '        internal sealed class MagicEvent { internal string Name; internal double Time; internal MagicEvent(string name,double time){Name=name;Time=time;} }',
         '        internal sealed class Motion { internal double Seconds,StateSpeed; internal bool AttackSpeed; internal Fire[] Fires; internal double[] Begins,Ends;',
         '            internal MagicEvent[] MagicEvents;',
         '            internal Motion(double seconds,double speed,bool scaled,Fire[] fires,double[] begins,double[] ends,MagicEvent[] magicEvents){Seconds=seconds;StateSpeed=speed;AttackSpeed=scaled;Fires=fires;Begins=begins;Ends=ends;MagicEvents=magicEvents;} }',
         '        internal static readonly Dictionary<string,Motion> States=new Dictionary<string,Motion>', '        {']
ledger = []
emitted = {}
for layer, machine in enumerate(data['m_Controller']['m_StateMachineArray']):
    if layer not in range(1, 8):
        continue
    for state_ref in machine['data']['m_StateConstantArray']:
        state = state_ref['data']
        refs = [node['data']['m_ClipID'] for tree in state['m_BlendTreeConstantArray'] for node in tree['data']['m_NodeArray'] if node['data']['m_ClipID'] != 4294967295]
        if len(refs) != 1:
            continue
        ref = data['m_AnimationClips'][refs[0]]
        if ref['m_FileID'] != 0:
            raise ValueError('External animation needs explicit asset resolution')
        clip = clips[(controller['file'], ref['m_PathID'])]
        key = str(layer) + ':' + names[state['m_NameID']]
        timing = clip['muscle_timing']
        duration = timing['m_StopTime'] - timing['m_StartTime']
        fires = [e for e in clip['events'] if e['functionName'] in fire_kinds]
        begins = [e['time'] for e in clip['events'] if e['functionName'] in begin_events]
        ends = [e['time'] for e in clip['events'] if e['functionName'] == 'EndAttackAnimation']
        magic_events = [e for e in clip['events'] if e['functionName'].startswith('MagicEventAnimation_')]
        speed_parameter = names.get(state['m_SpeedParamID'], '')
        if speed_parameter not in ('', 'AttackSpeed'):
            raise ValueError((key, speed_parameter))
        fire_text = ','.join('new Fire(%d,%d,%s)' % (fire_kinds[e['functionName']], e['intParameter'], number(e['time'])) for e in fires)
        magic_text = ','.join('new MagicEvent(%s,%s)' % (json.dumps(e['functionName']), number(e['time'])) for e in magic_events)
        value = 'new Motion(%s,%s,%s,new Fire[]{%s},new double[]{%s},new double[]{%s},new MagicEvent[]{%s})' % (
            number(duration), number(state['m_Speed']), str(speed_parameter == 'AttackSpeed').lower(), fire_text, ','.join(map(number, begins)), ','.join(map(number, ends)), magic_text)
        if key in emitted and emitted[key] != value:
            raise ValueError('Conflicting state identity: ' + key)
        if key not in emitted:
            lines.append('            {%s,%s},' % (json.dumps(key), value))
            emitted[key] = value
        ledger.append({'key': key, 'clip': clip['name'], 'duration': duration, 'speed': state['m_Speed'], 'parameter': speed_parameter,
                       'fires': fires, 'begins': begins, 'ends': ends, 'magic_events': magic_events, 'transitions': state['m_TransitionConstantArray']})
lines += ['        };', '    }', '}']
(ROOT / 'DpsMotions.cs').write_text('\n'.join(lines) + '\n', encoding='utf-8')
target = ROOT / 'evidence/dps/motion-states.json'
target.parent.mkdir(parents=True, exist_ok=True)
target.write_text(json.dumps(ledger, ensure_ascii=False, indent=2), encoding='utf-8')
print('Generated %d distinct animation states.' % len(emitted))
